### ISSUE TITLE
Unable to convert .reg file.

### ISSUE THREAD

**Issue by helmerzNL** [rzander/Reg2CI#1]
Windows Registry Editor Version 5.00

; ------ Enable Citrix Netscaler Gateway icon in tasktray ------
[HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\Secure Access Client]
"AllowCleanup"=dword:00000001
"DisableIconHide"=dword:00000001

; ------ Enable IE Enterprise Mode ------
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main\EnterpriseMode]
"Enable"=""

; ------ Block Execution of Macros in Office2016 documents coming from the internet  ------
[HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\office\16.0\excel\security]
"blockcontentexecutionfrominternet"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\office\16.0\powerpoint\security]
"blockcontentexecutionfrominternet"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\office\16.0\word\security]
"blockcontentexecutionfrominternet"=dword:00000001

; ------ Prevent First Things First, Word File format dialog and Skype quick tips and Help Skype improve window  ------
; 13Oct2017 - not allowed to deploy these improvements
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\General]
"ShownFileFmtPrompt"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Lync]
"IsBasicTutorialSeenByUser"=dword:00000001
"UserConsentedTelemetryUpload"=dword:00000000

;[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Outlook\setup]
;"DisableOffice365SimplifiedAccountCreation"=dword:00000000

; ------ Add https://autodiscover.delagelanden.com to local intranet zone Sites (to prevent certificate popups Outlook/Skype and perform autologon)  ------
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\customer.com\autodiscover]
"https"=dword:00000002

;Supress Autodiscover redirect warning for autodiscover.delagelanden.com
[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\AutoDiscover\RedirectServers]
"autodiscover.customer.com"=hex(0):

[HKEY_CURRENT_USER\Software\Microsoft\Exchange]
"AlwaysUseMSOAuthForAutoDiscover"=dword:00000001

; ------ Set Trusted Domain List (to prevent certificate warnings because autodiscover domain is different than mail domain (see KB2833618) ------ 
[HKEY_CURRENT_USER\software\policies\microsoft\office\16.0\lync]
"trustmodeldata"="lync.com, lync.glbdns.microsoft.com, microsoftonline.com, outlook.com"

;  ------ Disable the cloud-based discovery logic because it conflicts with our hybrid setup (see KB3135145) ------ 
;[HKEY_LOCAL_MACHINE\software\policies\microsoft\office\16.0\lync]
;"DisableCloudBasedDiscovery"=dword:00000001

**Comment by rzander** [comment]
It seems it's the line: 
`"autodiscover.customer.com"=hex(0):`
will check that...

**Comment by rzander** [comment]
Fixed (hopefully) in Reg2CI V 0.7.4.1 and Reg2PS V 1.0.3.1

**Comment by helmerzNL** [comment]
It is indeed fixed! Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
