### ISSUE TITLE
Issues with registry paths containing asterisk (*)

### ISSUE THREAD

**Issue by Gargauth** [rzander/Reg2CI#2]
Output of the script will hang powershell if registry paths contain asterisk  `*`.
Solution for this is to prepend `-LiteralPath`

For example:

```powershell
if((Test-Path "HKLM:\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\7-Zip") -ne $true) {  New-Item "HKLM:\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\7-Zip" -force -ea SilentlyContinue };
```

to

```powershell
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\7-Zip") -ne $true) {  New-Item -LiteralPath  "HKLM:\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\7-Zip" -force -ea SilentlyContinue };
```

It's rare enough issue that is easy to fix by hand, just thought I'd share it.

Thanks a lot for the script by the way, very handy!!!

**Comment by rzander** [comment]
Thanks, will fix that with the next Version...

**Comment by rzander** [comment]
FYI, New-Item does not accept a -LiteralPath Parameter

**Comment by Gargauth** [comment]
Yes, seems I was too hasty with that solution. I just tested it and it does only hang on `Test-Path` and `New-ItemProperty` , both of them fortunately accept and need `-LiteralPath`  parameter.  `New-Item` works without any modification.

**Comment by rzander** [comment]
Should be fixed: http://reg2ps.azurewebsites.net/
