### ISSUE TITLE
Registry Path with no Key Value doesn't provide a test check (it does provide a remediation script)

### ISSUE THREAD

**Issue by OftKilted** [rzander/Reg2CI#4]
To Replicate:

Enter:
`[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned]
`
Into the 'Registry to Powershell' field and select 'Get Check Script'
The result is:
```
# Reg2CI (c) 2019 by Roger Zander
try {
}
catch { return $false }
return $true

```
(It's missing what it's supposed to be checking.)

When one selects 'Get Remediation Script' there is a remediation script provided:
```
# Reg2CI (c) 2019 by Roger Zander
if((Test-Path -LiteralPath "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned") -ne $true) {  New-Item "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned" -force -ea SilentlyContinue };

```

**Comment by rzander** [comment]
Fixed in https://github.com/rzander/Reg2CI/commit/23986e573075a4c618b5d55833f90e27e012dbbc
