### ISSUE TITLE
Issue with adding multiple strings as values with spaces. 

### ISSUE THREAD

**Issue by ghost** [rzander/Reg2CI#5]
Wanted to inform you something I found. 

Registry I put in the converter.
[HKEY_CLASSES_ROOT\PhotoViewer.FileAssoc.Png\shell\open\command]
@=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,74,00,25,\
  00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,72,00,75,00,\
  6e,00,64,00,6c,00,6c,00,33,00,32,00,2e,00,65,00,78,00,65,00,20,00,22,00,25,\
  00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,46,00,69,00,6c,00,65,00,73,00,\
  25,00,5c,00,57,00,69,00,6e,00,64,00,6f,00,77,00,73,00,20,00,50,00,68,00,6f,\
  00,74,00,6f,00,20,00,56,00,69,00,65,00,77,00,65,00,72,00,5c,00,50,00,68,00,\
  6f,00,74,00,6f,00,56,00,69,00,65,00,77,00,65,00,72,00,2e,00,64,00,6c,00,6c,\
  00,22,00,2c,00,20,00,49,00,6d,00,61,00,67,00,65,00,56,00,69,00,65,00,77,00,\
  5f,00,46,00,75,00,6c,00,6c,00,73,00,63,00,72,00,65,00,65,00,6e,00,20,00,25,\
  00,31,00,00,00

What the converter gave me. 
New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\PhotoViewer.FileAssoc.Png\shell\open\command' -Name '(default)' -Value "%SystemRoot%\System32\rundll32.exe "%ProgramFiles%\Windows Photo Viewer\PhotoViewer.dll", ImageView_Fullscreen %1" -PropertyType ExpandString -Force -ea SilentlyContinue;

What I had to do to get it to work. I had to put another set of " around the %ProgramFiles%\Windows Photo Viewer\PhotoViewer.dll . When only one set, it would stop at Windows due to the space. This happened with 3 other registries that were similar. 

New-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Classes\PhotoViewer.FileAssoc.Png\shell\open\command' -Name '(default)' -Value "%SystemRoot%\System32\rundll32.exe ""%ProgramFiles%\Windows Photo Viewer\PhotoViewer.dll"", ImageView_Fullscreen %1" -PropertyType ExpandString -Force -ea SilentlyContinue;

**Comment by rzander** [comment]
Thanks, I will check...

**Comment by rzander** [comment]
Fixed: https://github.com/rzander/Reg2CI/commit/e138de8bcf8a3c0ec8b419c4fc117d9f658d8315
I also realized /fixed that an Expand_SZ string must expand environment variables when checking...
